version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.1.0
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Validate
          command: npm test
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/node-cache
  deploy_production:
    docker:
      - image: circleci/node:10.1.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: npm run gh-pages

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /^release-.*/
  build_deploy_production:
    jobs:
      - deploy_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-.*/
